apiVersion: v1
kind: Secret
metadata:
    name: bot-bazos
    namespace: dp-reality
    labels:
        app.kubernetes.io/part-of: dp-reality
type: Opaque
data:
    MONGODB_URI: ENC[AES256_GCM,data:QZ+pyd9oQOcMP2ehA/dspcoX7+uamPvEu73kPaqJu09G1VUkwKfRqWCbzNwyPRT5Setr6vUqd2DWd94IzXlabKZ3N+ySjJ4/F5jYjPhAVvdpG7vpU8zBDwYAzdR3Q64PA/RtpH0FUpV60eGlAig5H1N2FlFB3LdE1SwZWTnUzBeIJqlMoMwfIPwr30dxJkdFQHHFNQI/eJpQfmlKwPNjVTGstb1A/OS1i6XdunNI/PdnHJzP,iv:wx9g7XXW9vahKNulwZ6uJGF2eKC6+hbxLOCmmi5hkG4=,tag:931SY8ioAn9yGZIDuZjfpQ==,type:str]
    RABBITMQ_URL: ENC[AES256_GCM,data:4G5q/f+A7wKZ9T4S27//FE8wpJcvkRiRSiq4hLCWzOhEZmIe6Ak9j15dXF4JYenUR0tsrdheDaoFNYmHJp/yzwXpw4QvpJV3y9XOnH36R+5nEwAS25jpNiEi3StOPBAymceWJLkFxGH1dmU4noPg7slDbGU=,iv:Xmm2tlvCZFASUNN4fa7+E3KcphaXtpdv9LXw2263H9s=,tag:Rp6wQFsyjoAYfrUFEIc8jQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCWXFuaVlhdTZ0c3RoMDRI
            WWRMbHZCQnI5NDhGWE9Qd3pBYlFBaTI0SlJBCkozYzl3UkhzNEp4ampjVStzNzV6
            QnVOMHdUK3E4N0JzTWtSRnI5UUVkS3cKLS0tIFhrV0J0dEZpSHBYUVpBcGhYS2wv
            TEhKVHNjamR3UWNLbkR5ZlErRkNDSUUKqo3i6bfNSy2B2/RMqRTCyWCpUp8p8E6I
            WuWH7qvfsymobyo+LN/cRLGWlOmdFqSuFupCs5AvV+gCPluEL/pc5A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ngv4hv04nvrlec92f6dwjxz3hrg5ythxdvwwcdjujnwezlth6ycsnahv7e
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-14T20:46:59Z"
    mac: ENC[AES256_GCM,data:6R6ULH314Ax1WqiezXT/Rz90SWoEzFqUVTBaq2Zij01T7Cv2TFw40jyd7WwVlbimZmxX49sogecgp6rj6+XlTgFsO5VShSKioKVL3y4U2WOETFpJrCKcsfwhsu4bgaYtcelkr9R6Vz7k8EBCFCeSNNGDBZ3Frjj1SutE++Oa2Es=,iv:POhhoo9MG7yujVsF0BZkS+NatyV4CaWtkBO9iXGahEw=,tag:mELTR2lmeueZgERkja4ZRA==,type:str]
    version: 3.13.0
