apiVersion: v1
kind: Secret
metadata:
    name: bot-sreality
    namespace: dp-reality
    labels:
        app.kubernetes.io/part-of: dp-reality
type: Opaque
data:
    MONGODB_URI: ENC[AES256_GCM,data:t4IgRex1GhWG6G4pW73oMZ0wz13WYu9waC9nDhxijYtE2tJ0uBX3vGNKv38Pz1YbQkpuGOSKHKOAbETY7VYKpPVxGaJbIuA4ZhmlD0S+GbxjnpImAsM7FOlVz5BmKs7xYk1fVbB5N13MGQpZYDvDEGzC628ZCmkKg/VZByi+EffHlAI73RprhZOKpqP9XI1J5AR1yD/H0KWaidwTxvv6vmFLuvVJ5IcJZ67zd5y8Ij1MDD7C,iv:QHXiW/mJwCwvYG8Y/A3qyY+a8AI9L0jR6tZohXaQidM=,tag:ldRjfAT8znv8wiEA0uSssQ==,type:str]
    RABBITMQ_URL: ENC[AES256_GCM,data:WcpHlfsSVpkTubmR5jHITN9TjJiZv+0Ol79y6zL9VWwVV80L2UF7hpx0CllOAd9BAjQdx963PXgjzPmEsmKP4od37T2s3piY6vS8W9jdVU53HAvSWF9TLBeNadObsvJbkTy0Xzi3vMJCF2MN99xuyXUyeN4=,iv:N44dIMZZpQWnop+AWIjsPEd5OKi4LojwoWvWm6Txufo=,tag:ZPwErdsvcFTMhcuF7dVlLQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhK1V1NnVNQm5PL1VwaVNz
            L01CQ0h4cVErQW9jN3VCelRIL3BUY3RFUVg0CjFveDYwREcvNlhxdW5yTWlwLzBt
            UXhqQVM4TUdjQjR5VXBiYnVLUHpkUlUKLS0tIHpnL0hKdFB1eTkwYXZ6VFdOSnVH
            MW1FWHcxYmtOU1JBb0FHZjFFOXpIZjQK6O3yqAkqQwgyq6RjVncGxkKi94GKXrzR
            pR1pX/DL6/XNHFMVrnMPRs82Bsh5Mi1GuToMhgjY8xShQnEiOc3DuA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ngv4hv04nvrlec92f6dwjxz3hrg5ythxdvwwcdjujnwezlth6ycsnahv7e
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-14T20:46:59Z"
    mac: ENC[AES256_GCM,data:0j1J4nlLkes89qp7b5/7Wf7Dke3jaK9fSi4cwVZ3Uzty4zkW7nE0DqzuuuX+gog0F0eGYMNd9Uux37ns1B81peNmr09d+seQHEL++FaDGStJxSTbU7El1ULJ378NUBCsyjv3VmRDicsJm5CNRD7IKvMSwLw4PuHczQKKJKWDPZ0=,iv:9vCKvdECr2PUB5xxduPrlAa7DuA+e1+60SVzmlFCNhc=,tag:ca6DQ91Ptwrg5hBAif47Bw==,type:str]
    version: 3.13.0
