apiVersion: v1
kind: Secret
metadata:
    name: bot-bezrealitky
    namespace: dp-reality
    labels:
        app.kubernetes.io/part-of: dp-reality
type: Opaque
data:
    MONGODB_URI: ENC[AES256_GCM,data:E+LuzqAE4NjoqCnNG6gD05Pu33WvnrKPOtuIkM4RtZh7FOPJZ0i9hin1LtrlY5zvYPZjaosepV6gZgyLSAJ26fnCaaBTrF4hF7pGK/Bw0MCHgw3EdzX0XctsDXSRTLkv+eIm20quFmf78YapYko3vrjbqiyCmaqdZDk82OE3OrWPcyhsAOyE0R47uJMdJqWK1yvnMUuRTyAfBZ7ytomdPzqiFcmTmvc0HMVXrdX8tHiTUrmC,iv:L8AO8uYxbLIOExRDcu4gO3NsNp7nWYzngo212FYNRA4=,tag:7+7gxKWJ2E3ehgmoo4uNPw==,type:str]
    RABBITMQ_URL: ENC[AES256_GCM,data:3nhtUsBHViBPyTgutgqn4rQFTafgP1Yw5eZhTs2m9wnFDvzT/EaGZIa5aCJX7JNcRduAD0RF26iZNeJlB9QuNYsm10hW95hTfBUEJIP9242yUrMupSD5KNlIdqwVXv+k1e3Rj+4luqBzVLJjS69PPR53dcc=,iv:aGrfBpQ9Q3+NxRP7y8dUTH/TUBd+1iEsU6EPQyZ7hZM=,tag:wg5RGD+NwroMPs1+mXw+Wg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOc3JzbENubVhlUGpiNnly
            UEVyMDYrZFFTN1A1TDNaYzYwNm9oTU9PY0FzCkh1WjhDK0oyVVpRRjlGckdpR21C
            MUthRStleVc3QW9QMEc4SS8rMlNCOWsKLS0tIEFBU1E5cEtjaEszRUpBbzh0K09t
            aHlib0xhMUkzTW9lRk5tTHRucmdvbjAKdXKhLm5XqPMJc8flvQHeoUPztfQTMzXL
            P9t9TMw2oyuO87LkyHNnt/gJlFEadxuquxWID+BePabJ07zezHYbzQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ngv4hv04nvrlec92f6dwjxz3hrg5ythxdvwwcdjujnwezlth6ycsnahv7e
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-15T16:21:07Z"
    mac: ENC[AES256_GCM,data:zbehTE0M5SS1q0hHykZReJQC2aHRSgjGWN4vzCJlAbIP/kpFoQ0mSh8bpRrQyvhD50cQnFOXByVrVsYI1vx6nAXgIJpEzbRUJNIiLjU2Z2/4+1htD0dTf8m8gMiHt/LxE3URMPMGcwnh9H/fiL66mm7g9cEPnrWLDilVRKpxCTE=,iv:Qos7lnBTT+uugHZGrxB5RAOTpPD9B8gz+JDvFOVwjrQ=,tag:NSCBg+CvysewWCNCBv4sPA==,type:str]
    version: 3.13.0
