apiVersion: v1
kind: Secret
metadata:
    name: email-notifier
    namespace: dp-reality
    labels:
        app.kubernetes.io/part-of: dp-reality
type: Opaque
data:
    MAIL_SMTP_LOGIN: ENC[AES256_GCM,data:zxK4i6n8EZMIWmsj6bH0VQ==,iv:J1n4R2CRRFzc8l8PZLcgIPm9eTFlP0Md+FrzWSLmvXI=,tag:mnYoczZnQlvl2MyiUuy3ag==,type:str]
    MAIL_SMTP_PASSWORD: ENC[AES256_GCM,data:hQMnkwqj1f8iiU1ENVDTLg==,iv:9IjoqW5d8n5MpG9vuQQodQBKek5xZd3Bukw1nw4DZRU=,tag:fYBuTSiQjnMgn3UK3fhj6w==,type:str]
    MONGODB_URI: ENC[AES256_GCM,data:h2JgJbTnwc+JtCIVWM6qurLH8zH2z8gjHMZrQR/3O+WnVxA0r6oCEyW8nXVEQNMUNblA5FNng88gRFx/DttB1Y02qoAtFuG33HU7ivPhR3Lov1UnqND9E0k1fhtI9yGvHY6dK2JS0p4zlC48HNAMFYqIFCudxKpSGuxeBsXKNhO0/PT6yYgmnqxAZRehfwNRVQmnz5it2D6P0sK4+l/iEi2qQWoY+RSW8rZKUpJw3AL5kVqz,iv:ruDznEvfLsewqpe4qRwTckAP4svyEzG1pscf0ZG6oLM=,tag:HbPo1+Er5FVjUtRN78Fehg==,type:str]
    RABBITMQ_URL: ENC[AES256_GCM,data:ZICzoe05nl5Ro+3Qe5ZSTOaBP27dA9kkqL/YSM7euTo2Rbgxk3ga5peI4br1W5V0LWZ5m9+6mv4MSwdWDHdeMXXi2wegekCZcxBjtCPv2RoyAFnGKaWpVhkfefqD7gJJFPTJXSKZYBVUD5YeUJvhHb92LBs=,iv:Sec+a99KuzPgZMXhK1jH7I8A7heMeO0JyupSVHQgCv8=,tag:1wmsTC654Dl6gALxJE/s6A==,type:str]
    UNSUBSCRIBE_SECRET: ENC[AES256_GCM,data:Mf4vaSfKkyEdyXQk1Jii5bmQS5EZVjL4Aj7WQ6S6I7aJvgnkoXEVIEXvmaX6vZpsgEnEhra70UJ9kDfsODSMAY40tbz9qC1jakTU6KvpEIqy9oEEFmgNJg==,iv:VFLnQKEX3kZrZQkIH8QaURtJwO9LFrmQkeoBaVd0Qfs=,tag:IvKPXvbFQeIB2i/wjsye8Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3T2pIOGVqQ2IwNlNjWmZa
            K2ZRZXpZNTJMSEsyVFVyVEdZYnYxdVRJUFRFCmJXdjdKVUk4SjdHUXFPKy9DTDZy
            NWF4NmxaWFJCYkJkUUNwS2U5Y3BLa1UKLS0tIHVSeVYraXA4SVF6cGM4MVBVWWdJ
            aDF1cjdudE1SZEVYZTBHV2VTaVErdGMKw9LI3t3oWFcOd9PnZo0B4UeXemSmdn3x
            0zLPjvRWHatfAJEvNASxjG6hsEz+3FT1dLssoeSwLvEtwL6fV5t5bA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ngv4hv04nvrlec92f6dwjxz3hrg5ythxdvwwcdjujnwezlth6ycsnahv7e
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-14T20:46:59Z"
    mac: ENC[AES256_GCM,data:0yHuqjYOjlywJrvyQZkeWvsuavj2/6K8PLZF8r/3h9OrhClAXnkcFrazgpe0TEhg/B9H777/tZN5/v8vg6WYBa2DZAYq2KUxA8asv5jzrkAdnhHJAif3hFX2i+HvvJwFDC/aSJZG84gzy0fYv72sr8Tmi9H+SF7puYpHwsqTQhg=,iv:MucPZN8ACM6JjnZZ6/NFdpm7qNoCcCDPhyZyARD6Ges=,tag:/y+o7qnpx8pdpANLenkk2w==,type:str]
    version: 3.13.0
