apiVersion: v1
kind: Secret
metadata:
    name: email-notifier
    namespace: dp-reality
    labels:
        app.kubernetes.io/part-of: dp-reality
type: Opaque
data:
    MAIL_SMTP_LOGIN: ENC[AES256_GCM,data:egHLHU2PjZXM3+drzz0ETvtW1VeIOlFB,iv:iajNAPPw+qVA/8IYhwDDX4Dr8R8AYFwdczII5d0RUaA=,tag:9T5+m6zOumbPHI7WeS+qdA==,type:str]
    MAIL_SMTP_PASSWORD: ENC[AES256_GCM,data:smKpz6IcRYgs08g2sCOR9JgHF6lzJXWfFgZWqKzl/+WgsvlEGn3dSLopb4A=,iv:f/6t4c/ZKL2uD+HZL+oQ2B5RmB0I3KrSWdWsTl6A0LY=,tag:iqFQ7utCVlz2XpG+v2qc8g==,type:str]
    MONGODB_URI: ENC[AES256_GCM,data:h2JgJbTnwc+JtCIVWM6qurLH8zH2z8gjHMZrQR/3O+WnVxA0r6oCEyW8nXVEQNMUNblA5FNng88gRFx/DttB1Y02qoAtFuG33HU7ivPhR3Lov1UnqND9E0k1fhtI9yGvHY6dK2JS0p4zlC48HNAMFYqIFCudxKpSGuxeBsXKNhO0/PT6yYgmnqxAZRehfwNRVQmnz5it2D6P0sK4+l/iEi2qQWoY+RSW8rZKUpJw3AL5kVqz,iv:ruDznEvfLsewqpe4qRwTckAP4svyEzG1pscf0ZG6oLM=,tag:HbPo1+Er5FVjUtRN78Fehg==,type:str]
    RABBITMQ_URL: ENC[AES256_GCM,data:ZICzoe05nl5Ro+3Qe5ZSTOaBP27dA9kkqL/YSM7euTo2Rbgxk3ga5peI4br1W5V0LWZ5m9+6mv4MSwdWDHdeMXXi2wegekCZcxBjtCPv2RoyAFnGKaWpVhkfefqD7gJJFPTJXSKZYBVUD5YeUJvhHb92LBs=,iv:Sec+a99KuzPgZMXhK1jH7I8A7heMeO0JyupSVHQgCv8=,tag:1wmsTC654Dl6gALxJE/s6A==,type:str]
    UNSUBSCRIBE_SECRET: ENC[AES256_GCM,data:Mf4vaSfKkyEdyXQk1Jii5bmQS5EZVjL4Aj7WQ6S6I7aJvgnkoXEVIEXvmaX6vZpsgEnEhra70UJ9kDfsODSMAY40tbz9qC1jakTU6KvpEIqy9oEEFmgNJg==,iv:VFLnQKEX3kZrZQkIH8QaURtJwO9LFrmQkeoBaVd0Qfs=,tag:IvKPXvbFQeIB2i/wjsye8Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3T2pIOGVqQ2IwNlNjWmZa
            K2ZRZXpZNTJMSEsyVFVyVEdZYnYxdVRJUFRFCmJXdjdKVUk4SjdHUXFPKy9DTDZy
            NWF4NmxaWFJCYkJkUUNwS2U5Y3BLa1UKLS0tIHVSeVYraXA4SVF6cGM4MVBVWWdJ
            aDF1cjdudE1SZEVYZTBHV2VTaVErdGMKw9LI3t3oWFcOd9PnZo0B4UeXemSmdn3x
            0zLPjvRWHatfAJEvNASxjG6hsEz+3FT1dLssoeSwLvEtwL6fV5t5bA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ngv4hv04nvrlec92f6dwjxz3hrg5ythxdvwwcdjujnwezlth6ycsnahv7e
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-15T12:06:55Z"
    mac: ENC[AES256_GCM,data:t4FvB6fbfZgDcAbdT11cggha91NnZX5eVEt9XFdginYW7cMY7wIZh21kmxzNrF5flMlqjhXZTYhyC4B9RkTWxDGZOQC+6slva5yYvljHrg5BM+2LEKR3dpxWfj+WDam1mh07vDOQFLGGwYfvkIU9wD4Pao9SVEr7GFqUe59e5qI=,iv:3azvxDdV/LaRUOSXyLbKnZ2259wd8SNYB//qaaAzavY=,tag:gpUpyN8BVHhKRXM44bf1tg==,type:str]
    version: 3.13.0
