apiVersion: v1
kind: Secret
metadata:
  name: email-notifier
  namespace: dp-reality
  labels:
    app.kubernetes.io/part-of: dp-reality
    app.kubernetes.io/component: notifier
    app.kubernetes.io/name: email-notifier
type: Opaque
stringData:
  MONGODB_URI: REPLACE_ME
  RABBITMQ_URL: REPLACE_ME
  MAIL_SMTP_LOGIN: REPLACE_ME
  MAIL_SMTP_PASSWORD: REPLACE_ME
  UNSUBSCRIBE_SECRET: REPLACE_ME
