apiVersion: v1
kind: Secret
metadata:
  name: frontend
  namespace: dp-reality
  labels:
    app.kubernetes.io/part-of: dp-reality
    app.kubernetes.io/component: bff
    app.kubernetes.io/name: frontend
type: Opaque
stringData:
  NUXT_MONGODB_URI: REPLACE_ME
  NUXT_RABBITMQ_URL: REPLACE_ME
  NUXT_UNSUBSCRIBE_SECRET: REPLACE_ME
  NUXT_SESSION_PASSWORD: REPLACE_ME
