apiVersion: v1
kind: Secret
metadata:
    name: frontend
    namespace: dp-reality
    labels:
        app.kubernetes.io/part-of: dp-reality
type: Opaque
data:
    NUXT_MONGODB_URI: ENC[AES256_GCM,data:iTWMA2VqnAVorgsBd6L5PTk1AbVh+2SEagtz6RlgOuyx9mZG2UXuIu8TDO5rAGYkkrBSWa7UEw7+lZtjW5Ur+nwZ9LK5LkcEQhN+9njNQRvQk7uNv1LZWL9okub+g3C3bASBclMW9nz+8ACKiK6Oah6NKADvZN7/M3A0QTniOOA5VlpS8J451FucFxVQ4ndQa0NsgIifOXDMh7Ql/QqyACaCfkercYm3JGpdlnb6B0jaGRsr,iv:CGmCsaFZ+W82oDspxjhwpwIi+iYiEp+79vhxBTOQnyU=,tag:g910M0zKu03IzPBY2fmi7g==,type:str]
    NUXT_RABBITMQ_URL: ENC[AES256_GCM,data:43gQBAG41L4NLjU1jN/dOod/4jAHmfBuvuOHxEOCHNQJIs4sT8JKYbBh0GkGeWBBKcnYHaO5R0JqNzqM1KH77rZPW2/pYQchK1QLOFR9kzefVjprAh4mLG8Owiak7cQUUPmUqenoMTp0h2vWXAxFCHgwFZA=,iv:AavG7rAlZhJaN3p4WYFAhJlOl92lamg4vRryzgH1LO4=,tag:+dFWl8dGgvcmXKGaRPjc0A==,type:str]
    NUXT_SESSION_PASSWORD: ENC[AES256_GCM,data:XVJ51r6bF1Z9noI+dLzoU1QZxuvFaUTIdlf59KiYiTnmdzjM0HTG0qBRGR/b6Y0gqQrGt5Y2V+QBsaUCDFgAgzzem8aX5pSnqknIH/3WsT4kZ26eqvD9gA==,iv:0eXxTt/idhxaHJ/sCOtuXl0GEeRSLHGYyBXK28XaS/w=,tag:QbTNBk6qOQrSufb31OtZWw==,type:str]
    NUXT_UNSUBSCRIBE_SECRET: ENC[AES256_GCM,data:s47ipQPRQZ0U/Fi4P66q1xBnWyodTVdw9U7d76Vkqs9UmvraWa5oUMEMY58dXqADGY79GbhpXPrtKlQdSF1fKarxct7U8LokdnuJtfTnBPqFPidEwzYWUQ==,iv:KedtI+/ZQq5EwSQFRS7I2AcwpvOYHEik7bsV5UPyhXk=,tag:pFIM7zw5oiqAE1zaB09JdA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwNWNDWFRnRTVDZU9qQlNr
            d0lPd1dQa0JHbVNhUEpBQlMrZExSTU9WS24wCmxWeWV6MzF0Nyt4Mk5Uem1Rb1JP
            R0JEL2RnWTA4RVhCNGZWS0tHVHJBb0UKLS0tIHBLVlhCUTZUdU90N2tIRWV6czR5
            dWVwRjdsS0hLZElONlFaR1o5bythNmMKbq/eCPFvPNzJ6EGpySXhAy5aK5vB+uCW
            mtqAL0IYZAljUoZvutEzHrAknaXd8sVbGHtW36acYL/LnWrD/sdqdA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ngv4hv04nvrlec92f6dwjxz3hrg5ythxdvwwcdjujnwezlth6ycsnahv7e
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-14T20:46:59Z"
    mac: ENC[AES256_GCM,data:tagrJymzYrcQlwCx4qn0iBsH0QSrXyZMYUZ7I84/KlavLqgC95lEhv/bjstTAueuTsAOAhKr+BTA4DDkuYjg0+ubeqjzh2Pm0YXM9V60fndNN9HkFhXyUKJ/bXftN5pmPE5WrUdA7krs9DSnXfVBtgbodoiq27BIqsh1XgAXJt4=,iv:Eglb+lgtF1Ms5kxqQWC+QRczU4hdOMw5l8weIwQ8vrg=,tag:CmIG/9ywqZhaKjM0fO872Q==,type:str]
    version: 3.13.0
