apiVersion: v1
kind: Secret
metadata:
    name: geo-cz
    namespace: dp-reality
    labels:
        app.kubernetes.io/part-of: dp-reality
        app.kubernetes.io/component: geo
        app.kubernetes.io/name: geo-cz
type: Opaque
stringData:
    MONGODB_URI: ENC[AES256_GCM,data:zpZKwQurwGptnZaflj774pFyMlHDVzoTsE6Y9PtoNXfPPjWg0JKZGVuha0/xEOAq5VNRkTn7nGRRyFGHpKk7wdBl1EOExEWdDbntjq+jGhO3dsaMZNK1g9ZwTSKj+1Tmsfsf6Jrl23m5toJKfn0g4pTcTcqvtoZX52f4z/efwawZ7l7OfwVK,iv:q2H20jbW4s+cPZdYlXSMEElfw9bgoGbb6eTFHp4VMfo=,tag:qRKPbvcLlWeUP8zLFh/FUw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKZEY5S0YzWHpSQzljdDdL
            a1E2WmV0dXpGakkzdkF6UWRtbm9ySk5Ja2w4CmcvZFEyRDBTZ21ZQjJNcUlMdnZU
            RWUwKzgzOFNOZjEyd1FIME8yNmIrNk0KLS0tIFJVTWJydSt1a3hFdDhxUHVwNjBD
            Z1VOdS81SzFqTkt4cnlDUGVzRVRJbXcKVX7UP/hM0fYn/K7WXJLVte7Ljkx/HPOL
            0YbNICKhqVUWJ/dBYq97Jv9y/oH/1GMXF0PJBP9y/e8Moc4e1xdF/A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ngv4hv04nvrlec92f6dwjxz3hrg5ythxdvwwcdjujnwezlth6ycsnahv7e
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-16T15:32:19Z"
    mac: ENC[AES256_GCM,data:rgvIRJUlM5rAvqLZz8r/Eas2dIiBbWxzPvdNLjLhUBO8VXjl1EDas2XtujQKWAllzfNBhvYiLIa8vLi7T7fO53li3xlD+QkvQtll/KLTSLlQ+rETpFYp6+4HIWdogfmgmroOCxy3b3gdmENUJ5JDL0qp3twc0q8VGfsTgoo4VBE=,iv:5Y6hiroS7bJ7BX81DGqw0uEFid4Ce2c+V8CG9R0Ssec=,tag:+Wfj/XaQFXgVpGPixYL7rg==,type:str]
    version: 3.13.0
