apiVersion: v1
kind: Secret
metadata:
    name: rabbitmq
    namespace: dp-reality
    labels:
        app.kubernetes.io/part-of: dp-reality
type: Opaque
data:
    RABBITMQ_DEFAULT_PASS: ENC[AES256_GCM,data:fOqHvJdy8KCnUWiaPFt20WLeJEorCTst5sDC6j/Wravdxju9oiOF5/cE4SUUThW363yTuQu9jyMBsji/7iUcCA==,iv:+BuaC0qyis7c5WeavwdFTPbCc36QgE/G0ZsY3TOo8qE=,tag:wMXCh22jSBaGXjNVk93lkw==,type:str]
    RABBITMQ_DEFAULT_USER: ENC[AES256_GCM,data:ig+/o+lbvpV35XCAs4QzXKvANvzOfJZr,iv:pLq2C9CW2Czuz9M4jmkw6koHMummxLoqvWEfz83c/EU=,tag:seMlEKyh1pioTR11DQBKxA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhS0NncHVIMmdGQXhoRnpk
            Mis0S25FOWMxVU9tZlR0MlQxNHVoWk0rcFVBCmsvM2tZdXZBdEt4czE2akphbm9S
            MjZZazVYckt2VnZVRU51MXNIODgveGsKLS0tIFoyMGtSTXdabk40b04xUHRNRFEx
            WlV1Tm14ay9VSmpKRCszN0Vsb2RWRTQKSE/9JtWwRr6F97b40/CMMVBrWvvJCjjS
            AZsCj7Tnfce/nEGkERuN1/6uIUMJE/W+Q6I+DlNlN2uyD4k3MbxkNA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ngv4hv04nvrlec92f6dwjxz3hrg5ythxdvwwcdjujnwezlth6ycsnahv7e
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-14T20:46:59Z"
    mac: ENC[AES256_GCM,data:uj4IvxLn2YwQGN3ceCejZh/V6saPlbZSQPeweDLKbMVdiJwmJ45AvJho4NY7C6vHngSCWVsmZkUyakHNWyNjz0oM/1Cpm3KKLDFATk18dsgS9JTtWi8sI67OSWgwMFr9Pod5lO8HXfiWQ8IP2aeioFGfpRRlY6uOoAMLdNbQZqM=,iv:6GeGARz19TQ5iCTr50VjlIAC74xN5snNNoFo65+jWfs=,tag:rfOKj92vak5/hwJwVqdcVw==,type:str]
    version: 3.13.0
