apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq
  namespace: dp-reality
  labels:
    app.kubernetes.io/part-of: dp-reality
    app.kubernetes.io/component: broker
    app.kubernetes.io/name: rabbitmq
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: REPLACE_ME
  RABBITMQ_DEFAULT_PASS: REPLACE_ME
