apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
  labels:
    app: whoami
spec:
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
      - name: whoami
        image: traefik/whoami
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: whoami
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "whoami-app"
    tailscale.com/tags: "tag:k8s-operator"
    tailscale.com/funnel: "true"
spec:
  ports:
  - port: 443
    targetPort: 80
    name: https
  selector:
    app: whoami
  type: ClusterIP

