apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: dp-reality
  labels:
    app.kubernetes.io/part-of: dp-reality
    app.kubernetes.io/component: broker
    app.kubernetes.io/name: rabbitmq
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: rabbitmq
  ports:
    - { name: amqp, port: 5672,  targetPort: 5672,  protocol: TCP }
    - { name: mgmt, port: 15672, targetPort: 15672, protocol: TCP }
