apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale
type: Opaque
stringData:
    client_id: ENC[AES256_GCM,data:lnQzATBaXAmej2UKCEOTexA=,iv:kTgoQWJ8Kip5AX5Tn583IlTukwNmLrl+IPQmWIrMKuo=,tag:9Aps5bCCKuOTJWiBZxW+zQ==,type:str]
    client_secret: ENC[AES256_GCM,data:MtL1jTqpCRuoajqcAabyg9fnjdAZIWF3qbeaEbdStQeDLWw3Ll3axEc1nl66Sxbx4MQZ5H/4SNXCsRNmHaLr7A==,iv:DC1OQyw/CgWFKFfxI7ZT7or+PPbuCwoXcvaaVbtxgcs=,tag:CHuZteYkhOtWcEWJoUrnLw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhc2xZRlQ2U1gzeDI2dXRy
            dCsyR1hZM2hNQTFnMi9VVXBFK1JGRGYwVTA4CmRscmZ1KytRT3F6Um45QndadDlP
            ZVVBRWxwSlkzZG9DT0M3SG42MDMydFUKLS0tIFJjWlNMRHFDNGxQSS85M2JRdi9h
            QlIwMENJTmYxTnMrc0VEVUVyWktNc3cKiZezaO7JMa6LITU1KqkDtAiFDpjIuHp6
            NcmRpDXseA+/WkY4mOUi4WHIoSiWpFzNTdXVhys6YyoRPk3pAZDm8w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ngv4hv04nvrlec92f6dwjxz3hrg5ythxdvwwcdjujnwezlth6ycsnahv7e
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-15T17:02:43Z"
    mac: ENC[AES256_GCM,data:i7DmfH4o77bABz+0SBUqYFJjAC3Qf/dxpsANCq13iJZwJj6u89mDZ/pEhJ6ALxhB1qf7s9OO3TmlMBrIc76voFFDCjdE0i1Qutbrcxoo/iOYqDECAiHdHQP1XqeQw9+5FKMaFL7jC/f+iAQ9IFahWsHmxrd4jOyPZIZJIL1Zl5g=,iv:eOTfFrE9Xg9KYneLiVUTykoOWhTKK8CJsbfHUkFHwGs=,tag:R2izBhKbCW35FeZEYkIjhg==,type:str]
    version: 3.13.0
