apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend
  namespace: dp-reality
  labels:
    app.kubernetes.io/part-of: dp-reality
    app.kubernetes.io/component: bff
    app.kubernetes.io/name: frontend
data:
  NODE_ENV: production
  OTEL_SERVICE_NAME: frontend
