apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - sources.yaml
  - ingress-nginx.yaml
  - prometheus.yaml
  - flagger.yaml
  - tailscale-operator.yaml
  - secrets/tailscale-operator-oauth.yaml
